### ISSUE TITLE
No documentation on CucumberConfig

### ISSUE THREAD

**Issue by pJunger** [acmcarther/cucumber-rs#44]
I just noticed that as the struct CucumberConfig is not reexported, its documentation is not published (and with it the usage of the interface is a bit oblique).

Can we publish the documentation without giving direct access to the struct?
Maybe _create_config_ should have been a static method (_new_) ...

**Comment by acmcarther** [comment]
Since its part of our public API (via create_config) it probably ought be reexported from crate root.

Do you foresee any issue in making it public?

**Comment by pJunger** [comment]
No, I don't really.

I originally separated the factory method from the struct just so that no further path separator was needed (compared to the previous _start_ function).
Although now I lean towards an embedded factory method - but I could live with both versions.
