### ISSUE TITLE
bootstrap_target & windows

### ISSUE THREAD

**Issue by pJunger** [acmcarther/cucumber-rs#45]
In features/support/fs.rs: bootstrap_target
cp command is not available in Windows.
I'm trying to fix the TODO soon.

**Comment by acmcarther** [comment]
Hopefully some useful background for you:

That method copies the current executables "target" directory into mock project so it doesn't need to recompile the shared dependencies.

If you can find a cargo crate for this, that would be awesome. When I wrote this, I coudn't find an easy solution that didn't require me to manually recurse down the file tree. Bleh.

**Comment by pJunger** [comment]
Ah, right! That rings a bell... Doesn't seem like there is a crate even now ...
Might take me a bit longer than expected.

**Comment by acmcarther** [comment]
burntsushi pulling through as always [with a directory walking crate, walkdir](https://docs.rs/crate/walkdir/0.1.7)

It still looks a bit involved, but that's a great start.

**Comment by pJunger** [comment]
That's the crate I tried to [use here](https://github.com/pJunger/cucumber/commit/8c8eb34deacc5f0228d0fedcac82c47a843a10b4). 
I still don't really know what goes wrong there - I hope I'll get to it on the weekend.

**Comment by acmcarther** [comment]
Feel free to put up a PR here even if its giving you more trouble than expected. I've got a little bit of experience doing fiddly file things in rust and might be able to help.

**Comment by pJunger** [comment]
Thanks for the offer! Opened #46.
